spring.application.name=Fluxboard whiteboard
# --- Konfiguracja PostgreSQL ---
# Adres bazy danych (localhost, bo Docker wystawił port 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/continuum
spring.datasource.username=admin
spring.datasource.password=password
# JPA / Hibernate (automatyczne tworzenie tabel)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Konfiguracja MongoDB ---
spring.data.mongodb.uri=mongodb://localhost:27017/continuum

# --- Konfiguracja Redis ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
